name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    CI:
        name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node_version: ['8', '10', '12']
                os: [ubuntu-latest, windows-latest]

        steps:
            -   uses: actions/checkout@v1
            -   name: Use Node.js ${{ matrix.node_version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node_version }}

            -   name: npm install, build, lint and test
                run: |
                    npm clean-install
                    npm run check
                    npm run build
                    npm test
    SONAR:
        needs: CI
        name: Update Sonarqube
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   name: Use Node.js 10
                uses: actions/setup-node@v1
                with:
                    node-version: '10'

            -   name: npm install, test and sonar
                run: |
                    npm clean-install
                    npm test
                    npm run sonar
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
